### ISSUE TITLE
preware.net doesn't resolve

### ISSUE THREAD

**Issue by Herrie82** [webos-internals/preware#4]
@rwhitby I'm not sure if @ka6sox reached out to you, but the servers have physically been moved recently and as a result the DNS for preware.net needs to be updated to reflect this. All other domains that are managed at @ka6sox's end such as nas-admin.org, webos-internals.org and webos-ports.org have already been updated to reflect the new location, however it seems preware.net is under your control?

The new IP is: 23.141.224.193

**Comment by rwhitby** [comment]
This has been resolved.

**Comment by Herrie82** [comment]
@rwhitby Cheers for sorting!
